spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ync?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 201311tz

server:
  port: 8080
  servlet:
    context-path: "/ccs"



